import Head from "next/head"
import { Inter } from "@next/font/google"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

import style from "../styles/Home.module.scss"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={style.home}>
                <div className={style.container}></div>
            </main>
        </>
    )
}
